# environment arguments
seed: 42
precision: bf16-mixed
strategy: ddp
accelerator: gpu

# data arguments
dataset: lrgb/peptides_struct
num_workers: 16
global_batch_size: 128

# model arguments
backbone: hf_hub:timm/vit_base_patch16_224.augreg_in21k
pretrained: True
interface: prob
sample_size: 1
eval_sample_size: 10
centering: True
pad_mode: circular
max_patch_dropout: 0.5

# training arguments
n_steps: 50000
optimizer: adamw
lr: 0.00001
lr_pretrained: 0.00001
lr_schedule: linear
lr_warmup: 5000
lr_warmup_scale: 0.
schedule_from: 0
weight_decay: 0.1
lr_decay_degree: 0.9
early_stopping_monitor: validation/mae_epoch
early_stopping_mode: min
early_stopping_patience: 100

# interface arguments
entropy_loss_scale: 0.1
noise_scale: 1.0
tau: 0.01
hard: True
interface_num_layers: 3
interface_hidden_dim: 64
interface_dropout: 0.1

# logging arguments
root_dir: experiments
data_dir: data
log_dir: logs
save_dir: checkpoints
load_dir: checkpoints
log_iter: 100
val_iter: 20000
save_iter: 20000
load_step: -1
